### ISSUE TITLE
フォームの必須項目をわかりやすく伝えるUIの検討

### ISSUE THREAD

**Issue by tomoktan** [GourmetHunt/web_landing#10]

**Comment by tomoktan** [comment]
✳︎ってワールドワイドなの？
そもそも必須項目だけにすべきでは？

**Comment by toshitakasan** [comment]
フォーム右下に「Required」をグルメハントカラーで挿入。

**Comment by toshitakasan** [comment]
@tomoktan @kyyamash @yutasai 
![form2](https://cloud.githubusercontent.com/assets/14027438/9595101/83ce9e24-509f-11e5-887e-93fadf8b610e.jpg)
チェックボタンはこんなかんじでしょうか。

**Comment by tomoktan** [comment]
@toshitakasan シンプルでいいと思います。
ちなみにexpandはやめる予定なので、moreのとこは無しにして、requiredありの場合のモックも見たいです！

**Comment by kyyamash** [comment]
@toshitakasan requireの件とかも揃った時点でコメントするわ！基本は @tomoktan と二人でガリガリ進めてくれ！

**Comment by toshitakasan** [comment]
@tomoktan 
こんな感じでしょうか？
![form2](https://cloud.githubusercontent.com/assets/14027438/9599176/8c3d6d24-50cc-11e5-9799-6382c0f2e6a8.jpg)

**Comment by tomoktan** [comment]
@toshitakasan ありがとうございます。
それとこのissueはrequiredについてのissueなのでランチ/ディナー選択の部分はそっちのissueにコメント移動します。
