### ISSUE TITLE
フォームのデザイン調整

### ISSUE THREAD

**Issue by tomoktan** [GourmetHunt/web_landing#11]
issue分割
- [x] フォームの必須項目をわかりやすく伝えるUIの検討 #10
- [x] 予算とフリーコメントをexpandしてるのをやめる #9
- [x] 予約を希望する日時のフォームを変更 #7

**Comment by kyyamash** [comment]
@tomoktan @toshitakasan 
必須かどうかのデザインどうなったんだっけ？

**Comment by tomoktan** [comment]
@kyyamash 別issueを建てます
https://github.com/GourmetHunt/web_landing/issues/37
