### ISSUE TITLE
metaタグの見直し・修正

### ISSUE THREAD

**Issue by yamashitak0830** [GourmetHunt/web_landing#15]

**Comment by kyyamash** [comment]
家のPCで修正
<title>GourmetHunt - Japan Restaurant Concierge</title>
<meta name="keywords" content="GourmetHunt,japan,gourmet,restaurant,travel,concierge">
<meta property="og:title" content="GourmetHunt - Japan Restaurant Concierge">
<meta property="og:image" content="img/ogp.png">
