### ISSUE TITLE
Analytics系のトラッキングコードを追加

### ISSUE THREAD

**Issue by yamashitak0830** [GourmetHunt/web_landing#16]
- [x] **GoogleAnalytics**
https://www.google.com/intl/ja_jp/analytics/

- [x] **mixpanel**
https://mixpanel.com/

詳細は別途説明します。

**Comment by kyyamash** [comment]
@tomoktan 
Google Tag Managerで管理しよう。コードはSlackに共有しといた。
https://www.google.com/intl/ja/tagmanager/

mixpanelで細かいところ分析するには別途追加で設定する必要あり。
https://mixpanel.com/help/reference/javascript-full-api-reference

実際に依頼するまでにどこが離脱しているのか調査したいから、下の項目でファネル作れるようにしたい。
・リクエストしてみるボタン
・各フォームにフォーカス（どこの入力項目まで進んでるか）
・決定ボタン（全部入力して決定ボタン押すところまでいくか）

細かい仕様は実際に話ながらにしよう。

**Comment by tomoktan** [comment]
@kyyamash mixpannelのコードも追加しました。
TagManager,mixpannel共にツールで確認後Closeさせてください。

**Comment by kyyamash** [comment]
@tomoktan ありがとう！ちゃんとトラッキングされてるね！
下の行はタグマネージャーに入れてるから削除して大丈夫！
https://github.com/GourmetHunt/web_landing/blob/develop/index.html#L33-L35

**Comment by kyyamash** [comment]
あとは取り込むだけなのでClose
