### ISSUE TITLE
サイト全体の文言・説明文チェック

### ISSUE THREAD

**Issue by yutasai** [GourmetHunt/web_landing#18]
文言チェックします

**Comment by tomoktan** [comment]
https://github.com/GourmetHunt/web_landing/blob/master/index.html#L66-L68
```

**Comment by kyyamash** [comment]
@yutasai これ木曜日中ぐらいまでには一度フィードバックほしい！

**Comment by yutasai** [comment]
文言ちょっと見なおしてみました。QAは、いくつか要素追加したほうがよいかもしれないと思って、ハラルとか、サポート範囲・予約変更・キャンセルに触れておく、日本語できなくてもOKの安心感とか入れ込んでみましたー。ご意見よろしく！
---------------------
■サービス説明
・あなたの興味を教えてください。
予約フォームに、日程やエリア、予算などを入力してください。
数回のメールのやり取りを経て、ご要望に合ったお店を複数店舗ご提案致します。


・提案が気に入ったら、予約・決済を行ないます。
お店が決まったら、私たちが予約を代行致します。予約完了後、$5のお支払いをお願いします。
もちろん、気に入ったお店がなければお金はかかりません。


・あとはお店に行くだけ。
当日、指定の時間にお店へ行けば、あなたの席が用意されています。
最高のグルメ旅行をお楽しみください。


■QA
・日本のお店だったらどこでも予約できますか？
日本には飲食店が約60万店舗あります。その中で、予約を受付けているお店が対象です。
寿司、天ぷらなど、あなたの興味はもちろん、ハラル対応などの要望にも合わせて提案致します。


・予約した後もサポートしていただけますか？
ご安心ください。予約後も、「詳しいメニューが知りたい」、「行き方を教えて欲しい」などのお問合せに応じて、
メールにてお客さまをサポートさせて頂きます。
予約の変更やキャンセルは、お店によってポリシーが異なりますので、対応できない場合もございます。


★以下、追加でどうかな？

・日本語ができなくても大丈夫ですか？
メニュー選びにご不安がありましたら、事前にご連絡ください。
私たちがお店にあなたのご希望をお伝えしておきます。
安心して、美味しいお料理をお楽しみください。

**Comment by kyyamash** [comment]
@yutasai 
いいねー！わかりやすくなった！ありがとう！
追加はしたほうが良さそうね！収まり悪いからQAを４つにしたいね。
キャンセルのところを１コ切り出すか、追加でQA足すか・・・どう思う？

**Comment by yutasai** [comment]
@kyyamash 
変更対応とキャンセルにも関連するかもしれないけど、どのくらいの時間見積もってサービス使ったらいいかユーザー迷うと思うから、モデルケース的な内容のQA追加するのがいいと思った！
実際の期日はどうするか検討は必要だけど、例として、
・どのようなスケジュールで利用すればよいですか？
利用希望日の1週間前までにはご依頼ください。お店をご提案致しますので、3日前には最終決定をお願い致します。予約が完了した時点で、再度ご連絡致します。予約完了後の変更やキャンセルは、お店のポリシーによりますので、対応できない場合もございます。

**Comment by kyyamash** [comment]
@yutasai 
たしかにね。実際依頼してから予約したいって言うまで１ヶ月ぐらい掛かるとか普通にありそうよね。
当日ももちろん受け付けるんだけど、一旦は海外から利用すること踏まえてのスパン書いとくか。

**Comment by kyyamash** [comment]
@yutasai 
フォームの方も一応チェックよろしく

**Comment by yutasai** [comment]
・提案を受けたら必ずお店を予約しなければいけないですか？
そんなことはありません。ご提案する中に気に入ったお店があっても、予約をしなければ、手数料の$5は発生しません。ご提案したお店の情報を参考にしてもらうだけでもOKです。

**Comment by kyyamash** [comment]
文言チェックOK！

**Comment by kyyamash** [comment]
取り込み完了
