### ISSUE TITLE
フォームの文言チェック

### ISSUE THREAD

**Issue by tomoktan** [GourmetHunt/web_landing#27]
**フォームのソース**
https://github.com/GourmetHunt/web_landing/blob/master/index.html#L199-L241

**Comment by yutasai** [comment]
英語にするから、フォームのラベル自体は、文章じゃくて項目名ベースに直しました。あとは、ホテル・エリア、最後のフリーフォームのplaceholder内の例文も見直しました。

・お名前／ニックネーム
Your Name or Nick Name

・メールアドレス
your@email.com

・滞在中のホテル名またはエリア
例） GRAND HYATT TOKYO
例） Roppongi

・予約を希望する日時

・予約人数

・一人当たりの予算

・具体的なご要望
料理ジャンルや店舗名が決まっている場合や、その他のお食事に関するご要望がありましたら教えてください。
例）Sushi、Tempura、Teppan-Yaki
例）ハラル対応を希望。乳製品にアレルギーがある。

**Comment by kyyamash** [comment]
取り込み完了
