### ISSUE TITLE
自動返信メールの内容を考える

### ISSUE THREAD

**Issue by tomoktan** [GourmetHunt/web_landing#3]
件名、本文をお願いしますー
英語で、ちなみにhtmlも使えます。

**Comment by toshitakasan** [comment]
下記文章でいかがでしょうか？
Voyaginを参考に考えました！


{ユーザーネーム}さん、こんにちは！
グルメハントへのお申し込みありがとうございます！

お申し込みの詳細は以下の通りとなります。

体験内容の詳細：
{フォーム入力内容が入る}


〈今後の流れ〉
頂いた情報を元に、グルメハントスタッフからいくつかの質問事項をメールさせて頂き、
数回のコミュニケーションを経てお勧めをピックアップさせて頂きます。

私たちの提案を気に入って頂けたら、
予約を代行、完了後$5を支払いをお願いします。
もちろん、気に入った店がなければお金はかかりません。

当日を迎えるまでに不明点等ございましたら、お気軽にお問い合わせください。 お客様に気持ちよく当日を迎えていただけるようサポートさせていただきます。
何卒よろしくお願いします。

The GourmetHunt Team GourmetHuntチーム https://www.gourmethunt.com/

**Comment by kyyamash** [comment]
いい感じね！一発目から何かしら提案するか、コミュニケーションしたあとで提案するか悩むね。
上の文面だと後者だけど。

@tomoktan @toshitakasan @yutasai 
それぞれご意見ください。

**Comment by toshitakasan** [comment]
@kyyamash 自動返信メールだから提案は難しくない？
エリアとか予算で登録しておいて出しちゃう？

**Comment by kyyamash** [comment]
@toshitakasan いや、その後の話かな。下のどっちがいいのかなと。
・①自動返信来る→②すぐ提案される→③違ったら希望言う→④再度提案される
・①自動返信来る→②色々ヒヤリングされる→③提案される

**Comment by toshitakasan** [comment]
@kyyamash 
食べたいものがきまっていますか？欄に何か入っていれば前者にして、
そうではない場合後者にする？

**Comment by toshitakasan** [comment]
{ユーザーネーム}さん、こんにちは！
グルメハントへのお申し込みありがとうございます！

お申し込みの詳細は以下の通りとなります。

体験内容の詳細：
{フォーム入力内容が入る}

〈今後の流れ〉
頂いた情報を元に、グルメハントスタッフが選ぶ
おすすめのレストランを後ほどご提案させて頂きます。

もちろんその中から選ぶ必要は無く、
数回のコミュニケーションを経ながら
納得が行く迄お店を提案させて頂きます。

私たちの提案を気に入って頂けたら、
予約を代行、完了後$5を支払いをお願いします。
もちろん、気に入った店がなければお金はかかりません。

当日を迎えるまでに不明点等ございましたら、お気軽にお問い合わせください。 お客様に気持ちよく当日を迎えていただけるようサポートさせていただきます。
何卒よろしくお願いします。

The GourmetHunt Team 
GourmetHuntチーム 
https://www.gourmethunt.com/

**Comment by kyyamash** [comment]
内容はOK！再チェックして翻訳。

**Comment by kyyamash** [comment]
@yutasai これ翻訳した後の取り込みはよろしく頼む。

**Comment by kyyamash** [comment]
翻訳終わったのでClose。取り込み作業は別issue
