### ISSUE TITLE
フォームの送信ボタンのデフォルトはdisableにする

### ISSUE THREAD

**Issue by kyyamash** [GourmetHunt/web_landing#31]
@tomoktan 
送信ボタン押されたらコンバージョンと定義しようと思うから、ボタンをdisableにして必須入力項目が全部入力されたらボタン押されるようにしてほしい！

**Comment by tomoktan** [comment]
@kyyamash JavaScriptの実装を大きく変えることになり、コストがかかるのでやりたくないです。
現在、必須項目が全て入力されている状態でボタンが押された時のみ「Purchased」というコンバージョンを表すイベントをmixpannelで投げてますので、現状のままでいいと思います。

```
mixpanel.track("Click SEND BUTTON");
```
を消す事で不要なイベントも送らなくなるので、そちらで対処します。

**Comment by kyyamash** [comment]
@tomoktan 
そんな感じで実装してるならそれで大丈夫！
同じイベントをAdwordsのコンバージョントラッキングでも拾えるようにしたいんだよね。

**Comment by kyyamash** [comment]
一旦クローズ
