### ISSUE TITLE
文字が見にくいのでメインビジュアル画像を暗くする

### ISSUE THREAD

**Issue by kyyamash** [GourmetHunt/web_landing#50]
@toshitakasan 出来ないようだったら教えて！俺対応する。

**Comment by toshitakasan** [comment]
@kyyamash 
焼き鳥の写真のみ？

**Comment by kyyamash** [comment]
@toshitakasan 
全体的に。前のサイト見たく斜線入れるとかの方が良さそうな気もするけど、そんなことない？
最終ジャッジ任せる！

![yakitori](https://cloud.githubusercontent.com/assets/14027473/9728190/43780a98-5641-11e5-8bbf-6de06c86383e.png)
![teppan](https://cloud.githubusercontent.com/assets/14027473/9728195/488db3ac-5641-11e5-9f65-556827065e52.png)
![sushi](https://cloud.githubusercontent.com/assets/14027473/9728198/4eff8bde-5641-11e5-92d7-c5a5a1445c99.png)

**Comment by kyyamash** [comment]
意外と大丈夫って気がしないでもない笑

**Comment by toshitakasan** [comment]
@kyyamash 
大丈夫なようなきがするw
若干調整します。

**Comment by toshitakasan** [comment]
@kyyamash コントラストを失わないように暗くしたよ！

**Comment by toshitakasan** [comment]
![slide1](https://cloud.githubusercontent.com/assets/14027438/9728352/317970b0-5642-11e5-8aea-4b6ac18876ed.jpg)
![Uploading slide2.jpg…]()
![Uploading slide3.jpg…]()

**Comment by toshitakasan** [comment]
![slide1](https://cloud.githubusercontent.com/assets/14027438/9728360/377e7672-5642-11e5-8e0b-36ab4a3086d7.jpg)
![slide2](https://cloud.githubusercontent.com/assets/14027438/9728358/377a3ff8-5642-11e5-9cce-e43072328d6b.jpg)
![slide3](https://cloud.githubusercontent.com/assets/14027438/9728359/377d8a3c-5642-11e5-9808-b7e39aaea674.jpg)

**Comment by toshitakasan** [comment]
@kyyamash 
差分データってどうすればよい？ここに添付？

**Comment by kyyamash** [comment]
@toshitakasan 
ありがとう！Google Driveのdesignフォルダ突っ込んどいてくれ！

**Comment by toshitakasan** [comment]
@kyyamash OK!
