### ISSUE TITLE
予約を希望する日時のフォームを変更

### ISSUE THREAD

**Issue by tomoktan** [GourmetHunt/web_landing#7]
- [x] 年月日までの入力にする
- [x] ディナーかランチを選択させるように修正
- [x] デフォルトで、今日の日付を入れておく

**Comment by tomoktan** [comment]
@tomoktan @kyyamash @yutasai 
![form2](https://cloud.githubusercontent.com/assets/14027438/9595101/83ce9e24-509f-11e5-887e-93fadf8b610e.jpg)
チェックボタンはこんなかんじでしょうか。

**Comment by tomoktan** [comment]
RT @tomoktan @toshitakasan シンプルでいいと思います。

**Comment by tomoktan** [comment]
RT @kyyamash 

@toshitakasan requireの件とかも揃った時点でコメントするわ！基本は @tomoktan と二人でガリガリ進めてくれ！

**Comment by tomoktan** [comment]
@toshitakasan 思ったんですけど、ランチ・ディナーの選択てチェックボックスじゃなくてラジオボタンんじゃないでしょうか？

**Comment by kyyamash** [comment]
確かに絞ったほうがこちら側からすると提案はしやすいね。両方チェックされた時にお店選び困るね。

**Comment by tomoktan** [comment]
チェックボックスにしておきますー。（見た目もチェックボックスに寄せるのであとでレビューしてください
）

**Comment by kyyamash** [comment]
将来的には両方チェックでも対応できるようにだな。
